name: actions_python_safety
description: Github action for running security vulnerability checks on python dependencies with safety
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  options:
    description: "additional flags/parameters to be passed to the safety command"
    required: false
    default: ""  
  pip_install_command: 
    description: "command used to install python dependancies"
    required: false
    default: "pip install safety"
  python_version:
    description: "version of python to run action with"
    required: false
    default: "3.x"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: "Setup Python ${{ inputs.python_version }}"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: "Show Python Version"
      run: python --version
      shell: bash

    # - name: "Install Python Dependencies"
    #   run: |
    #     python -m pip install --upgrade pip
    #     ${{ inputs.pip_install_command }}
    #   shell: bash
       
    - name: "Run Safety"
      run: |
        python -m pip install --upgrade pip
        ${{ inputs.pip_install_command }}
        safety ${{ inputs.options }} check
      shell: bash
